[LUM-860] Upgrade to new JS SDK
lum-network/chain-bridge pull request #144
Opened 2024-02-07 03:53 UTC by ThibaultJRD

### Introduction

This PR upgrades all the chain bridge to new LUM JS SDK

### Testing

Test everything again

2024-02-07 09:59 UTC, Segfaultd requested changes

2024-02-07 09:59 UTC, Segfaultd commented on package.json
> +        "@lum-network/sdk-javascript-legacy": "npm:@lum-network/sdk-javascript@0.8.9",
Remove legacy

2024-02-07 09:59 UTC, Segfaultd commented on src/async/consumers/asset.consumer.ts
> +import { ProposalStatus } from '@lum-network/sdk-javascript/build/codegen/cosmos/gov/v1/gov';
We use v1beta1

2024-02-07 09:59 UTC, Segfaultd commented on src/async/consumers/block.consumer.ts
> +(BigInt.prototype as any).toJSON = function () {
It has nothing to do here

2024-02-07 09:59 UTC, Segfaultd commented on src/async/consumers/block.consumer.ts
> +                console.log(hash);
?

2024-02-07 09:59 UTC, Segfaultd commented on src/async/consumers/block.consumer.ts
> +                console.log('Logs: ', logs);
?

2024-02-07 09:59 UTC, Segfaultd commented on src/async/schedulers/validator.scheduler.ts
> +import { LumRegistry as LumLegacyRegistery } from '@lum-network/sdk-javascript-legacy';
Remove legacy

2024-02-07 09:59 UTC, Segfaultd commented on src/http/controllers/accounts.controller.ts
> +                            amount: parseInt(rwd.amount, 10),
Where did the precision go?

2024-02-07 09:59 UTC, Segfaultd commented on src/http/controllers/accounts.controller.ts
> +                                    amount: parseInt(rwd2.amount, 10),
Where did the precision go?

2024-02-07 09:59 UTC, Segfaultd commented on src/services/chains/generic.chain.ts
> +        const legacyClient = await LumLegacyClient.connect(useEndpoint, (error) => {
Remove legacy client

2024-02-07 10:01 UTC, Segfaultd commented
Please make proper PR description.

2024-02-09 14:56 UTC, ThibaultJRD commented on src/http/controllers/accounts.controller.ts
> +                            amount: parseInt(rwd.amount, 10),
We don't need this anymore

2024-02-14 09:51 UTC, merged